feat: create a new plugin for qBittorrent #769
torrust/torrust-index-backend pull request #773
Opened 2024-11-16 09:50 UTC by hungfnt

The implementation is somewhat simple. I included the .py file in the torrust-index repo. 
Should we consider add a new repo to publish our plugin to the [unofficial search plugins list](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins).

![image](https://github.com/user-attachments/assets/11fc273f-61bf-48f0-a52b-eff7b0a0cf01)

2024-11-16 10:08 UTC, josecelano commented
Hi @hungfnt thank you!! I will test it in the next days.

> Should we consider creating a new repository to publish our plugin to the  [unofficial search plugins list](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins) once the demo is complete?

I think we can live in this repo template so Torrust Index users can build their specific plugins. I'm moving this concrete implementation to https://github.com/torrust/torrust-demo, where I'm putting all the code related to the demo index and tracker. I still have to move the [docker-compose configuration](https://github.com/torrust/torrust-compose/tree/main/droplet) I'm using for the demo from the [torrust-compose](https://github.com/torrust/torrust-compose/tree/main/droplet) repo.

2024-11-18 09:52 UTC, josecelano requested changes
Hi @hungfnt I was able to search for a torrent and It's correctly added in the search results:

![image](https://github.com/user-attachments/assets/8ce2c374-3a9f-4fea-873b-2698e0a35670)

However, when I try to download it. It's added to the downloading list with the infohash instead of the name:

![image](https://github.com/user-attachments/assets/bbcd19fa-d6af-4995-ad15-6d4c12301b08)

And it has no trackers. I don't know how these bqittorrent plugins work, but if it uses the magnet link, I guess we need to add these fields to the magnet-link:

- tr (tracker address)
- dn (display name)

See https://en.wikipedia.org/wiki/Magnet_URI_scheme

You don't need to build the magnet-link it's in the API details response: https://index.torrust-demo.com/api/v1/torrent/443c7602b4fde83d1154d6d9da48808418b181b6.

If it's not possible to call another endpoint I can include the magnet-link in the search API endpoint. Let me know and I will open a new issue for that.

2024-11-18 12:28 UTC, hungfnt commented
Hi @josecelano, I believe that using just the magnet link with the infohash is sufficient. It might be slow when downloading metadata, so you could try it on a different machine or network. The current table layout also utilizes the magnet link with the infohash only.

2024-11-18 12:41 UTC, josecelano commented
> Hi @josecelano, I believe that using just the magnet link with the infohash is sufficient. It might be slow when downloading metadata, so you could try it on a different machine or network. The current table layout also utilizes the magnet link with the infohash only.

OK @hungfnt. I will merge it to give you credit for you contribution but I think I will move this concrete implementation to https://github.com/torrust/torrust-demo. You can also open a PR there.

I think we should include in this repo only a kind of documentation explaining how to build and customize this plugin for your Index. Maybe I will move it later to another dir (maybe docs).

2024-11-18 13:02 UTC, hungfnt commented
I've opened a PR [here](https://github.com/torrust/torrust-demo/pull/18).

2024-11-18 15:24 UTC, josecelano commented
> I've opened a PR [here](https://github.com/torrust/torrust-demo/pull/18).

Thank you!!

2024-11-18 15:24 UTC, closed without merging